src/Entity/Adress.php
<?php

namespace App\Entity;

use App\Repository\AdressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AdressRepository::class)]
class Adress
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 3,
        minMessage: "L'adresse ne peut pas faire moins de {{ limit }} caractères",
        max: 255,
        maxMessage :"L'adresse' ne peut pas faire plus de {{ limit }} caractères"
    )]
    private ?string $adress = null;

    #[ORM\Column(length: 5)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 5,
        minMessage: "Le code postal doit faire exactement {{ limit }} caractères",
        max: 5,
        maxMessage :"Le code postal doit faire exactement {{ limit }} caractères"
    )]
    private ?string $zip_code = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 3,
        minMessage: "Le nom de la ville ne peut pas faire moins de {{ limit }} caractères",
        max: 255,
        maxMessage :"Le nom de la ville ne peut pas faire plus de {{ limit }} caractères"
    )]
    private ?string $city = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'adresses')]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): static
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addAdress($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeAdress($this);
        }

        return $this;
    }
}

src/Form/UserType.php
<?php
// src/Form/UserType.php
namespace App\Form;

use App\Entity\User;
use App\Entity\Adress;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => [
                    'placeholder' => 'admin@test.com'
                ],
                'required' => true,
            ])
            ->add(
                'password',
                RepeatedType::class,
                [
                    'type' => PasswordType::class,
                    'invalid_message' => 'Les mots de passe doivent être identiques',
                    'first_options' => [
                        'label' => "Mot de passe",
                        'attr' => [
                            'placeholder' => 'Test12345',
                        ],
                        'constraints' => [
                            new NotBlank(),
                            new Length([
                                'max' => 4000,
                            ]),
                            new Regex([
                                'pattern' => "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{8,}$/",
                                'message' => "Le mot de passe doit contenir au moins une lettre minuscule, une lettre majuscule, un chiffre et un caractère spécial, et doit être d’au moins 8 caractères de long."
                            ]),
                        ],
                    ],
                    'second_options' => [
                        'label' => 'Confirmer le mot de passe',
                        'attr' => [
                            'placeholder' => 'Test12345',
                        ],
                    ],
                    'mapped' => false,
                    'required' => true,
                ]
            );

        if ($options['isAdmin']) {
            $builder->remove('password')
                ->add('roles', ChoiceType::class, [
                    'label' => 'Rôles',
                    'choices' => [
                        'Utilisateur' => 'ROLE_USER',
                        'Admin' => 'ROLE_ADMIN',
                    ],
                    'expanded' => true,
                    'multiple' => true,
                ]);
        }

        if($options['isEdit']) {
            $builder
                ->add('adresses', EntityType::class, [
                    'class' => Adress::class,
                    'choice_label' => 'adress',
                    'multiple' => true,
                ])
                ->add('first_name', TextType::class, [
                    'label' => 'Prénom'
                ])
                ->add('last_name', TextType::class, [
                    'label' => 'Nom'
                ])
                ->add('telephone', TextType::class, [
                    'label' => 'Téléphone'
                ])
                ->add('birth_date', null, [
                    'label' => 'Date de naissance',
                    'widget' => 'single_text',
                ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'isAdmin' => false,
            'isEdit' => false,
            'user' => null,
            'sanitize_html' => true,
        ]);
    }
}

src/Controller/BackEnd/UserController.php
<?php

namespace App\Controller\Backend;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/users', name: 'app.admin.users')]
class UserController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $em,
    ) {
    }


    #[Route('', name: '.index', methods: ['GET'])]
    public function index(UserRepository $userRepo): Response
    {
        return $this->render('Backend/Users/index.html.twig', [
            'users' => $userRepo->findAll(),
        ]);
    }
    #[Route('/{id}/update', name: '.update', methods: ['GET', 'POST'])]
    public function update(?User $user, Request $request): Response | RedirectResponse
    {
        if (!$user) {
            $this->addFlash('error', 'Utilisateur non trouvé');

            return $this->redirectToRoute('app.admin.users.index');
        }
        $form = $this->createForm(UserType::class, $user, ['isAdmin' => true]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($user);
            $this->em->flush();

            $this->addFlash('success', 'Utilisateur modifié avec succès');
            return $this->redirectToRoute('app.admin.users.index');
        }

        return $this->render("Backend/Users/update.html.twig", [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: '.delete', methods: ['POST'])]
    public function delete(?User $user, Request $request): RedirectResponse
    {
        if (!$user)
        {
            $this->addFlash('error', 'Utilisateur non trouvé');
            return $this->redirectToRoute('app.admin.users.index');
        }

        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('token')))
        {
            $this->em->remove($user);
            $this->em->flush();
            $this->addFlash('success', 'Utilisateur supprimé avec succès');
        }else
        {
            $this->addFlash('error', 'Token CSRF invalide');
        }
        return $this->redirectToRoute('app.admin.users.index');
    }
}

src/Controller/Frontend/AdressController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Adress;
use App\Form\AdressType;
use App\Repository\AdressRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

#[Route('/users/adress', name: 'app.users.adress')]
class AdressController extends AbstractController
{

    public function __construct(private EntityManagerInterface $em)
    {
    }

    #[Route('', name: '.index', methods: ['GET'])]
    public function index(AdressRepository $adressRepository): Response
    {

        return $this->render('Frontend/adress/index.html.twig', [
            'adresses' => $adressRepository->findAll()
        ]);
    }

    #[Route('/create', name: '.create', methods: ['GET', 'POST'])]
    public function create( Request $request): Response | RedirectResponse
    {
        $adress = new Adress;

        $form = $this->createForm(AdressType::class, $adress);
        $form->handleRequest($request);

        if ($form->isSubmitted()  && $form->isValid()) {
            $this->em->persist($adress);
            $this->em->flush();
            $this->addFlash('success', 'Vous venez de créer une adresse');

            return $this->redirectToRoute('app.users.adress.index');
        }

        return $this->render(
            'Frontend/Adress/create.html.twig',
            ['form' => $form]
        );
    }

    #[Route('/{id}/update', name: '.update', methods: ['GET', 'POST'])]
    public function update(Request $request, ?Adress $adress, AdressRepository $adressRepository): Response | RedirectResponse
    {
        if (!$adress) {

            $this->addFlash('error', 'L\adresse n\'a pas été trouvée');

            return $this->redirectToRoute('app.users.adress.index');
        }

        $form = $this->createForm(AdressType::class, $adress);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->em->persist($adress);
            $this->em->flush();
            $this->addFlash('success', 'Adresse modifiée avec succès');

            return $this->redirectToRoute('app.users.adress.index');
        }

        return $this->render('Frontend/adress/update.html.twig', [
            'form' => $form
        ]);
    }
    #[Route('/{id}/delete', name: '.delete', methods: ['POST'])]
    public function delete(?Adress $adress, Request $request): RedirectResponse
    {
        if (!$adress) {

            $this->addFlash('error', 'Adresse pas trouvée');

            return $this->redirectToRoute('app.users.adress.index');
        }

        if ($this->isCsrfTokenValid('delete' . $adress->getId(), $request->request->get('token'))) {
            $this->em->remove($adress);
            $this->em->flush();
            $this->addFlash('success','Adresse supprimée avec succès');

            return $this->redirectToRoute('app.users.adress.index');
        } else {
            $this->addFlash('error', 'Vous avez le mauvais token');
        }
        return $this->redirectToRoute('app.users.adress.index');
    }
}

templates/Frontend/Users/_form.html.twig
{{ form_start(form) }}

{{ form_widget(form) }}

<button type="submit" class="btn btn-primary">{{buttonLabel}}</button>

{{ form_end(form) }}

templates/Frontend/Users/adress.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Mes adresses
	{{ parent() }}
{% endblock %}

{% block body %}

	<h2>Adresses</h2>
	<ul>
		{% for adress in user.adresses %}
			<li>
				{{user.firtname}},
                {{user.lastname}}
			</li>
			<li>
				{{ adress.adress }}
			</li>
			<li>
				{{ adress.zipCode }},
				{{ adress.city }},
			</li>
			<a href="{{ path('app.users.adress.update', { id: adress.id }) }}" class="btn btn-primary">Modifier</a>
		{% else %}
			<li>Aucune adresse trouvée.</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/Frontend/Users/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Modification du profil
    {{ parent() }}
{% endblock %}

{% block body %}
<div class="profile-wrapper">
    <div class="profile-container">
        <h1 class="title text-center">Mes informations</h1>
        <p class="subtitle text-center">Mettez à jour vos informations personnelles</p>
        <form action="" method="post">
            <div class="form-group">
                <label for="firstName" class="form-label">Prénom:</label>
                <input type="text" id="firstName" name="firstName" class="form-control" value="{{ user.firstName }}" required />
            </div>
            <div class="form-group">
                <label for="lastName" class="form-label">Nom:</label>
                <input type="text" id="lastName" name="lastName" class="form-control" value="{{ user.lastName }}" required />
            </div>
            <div class="form-group">
                <label for="birthDate" class="form-label">Date de naissance:</label>
                <input type="date" id="birthDate" name="birthDate" class="form-control" value="{{ user.birthDate|date('Y-m-d') }}" required />
            </div>
            <div class="form-group">
                <label for="phone" class="form-label">Téléphone:</label>
                <input type="text" id="phone" name="phone" class="form-control" value="{{ user.telephone }}" required />
            </div>
            <div class="form-group">
                <label for="email" class="form-label">Email:</label>
                <input type="email" id="email" name="email" class="form-control" value="{{ user.email }}" required />
            </div>
            <div class="form-group">
                <label for="password" class="form-label mt-2">Nouveau mot de passe:</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="*****" required />
            </div>
            <div class="form-group">
                <label for="confirmPassword" class="form-label mt-2">Confirmer mot de passe:</label>
                <input type="password" id="confirmPassword" name="confirmPassword" class="form-control" placeholder="*****" required />
            </div>
            <div class="form-group mt-4 text-center">
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                <button type="submit" class="btn btn-primary btn-block">Mettre à jour mon profil</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/Frontend/Users/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Modification votre profil
    {{ parent() }}
{% endblock %}

{% block body %}
    <section class="container mt-5 admin-brands-container">
        <h1 class="text-center mb-4">Modifier une adresse</h1>
        {% include 'Frontend/Users/_form.html.twig' %}
        <a href="{{ path('app.users.adress.index') }}" class="btn btn-secondary mt-3">Retour à la liste</a>
    </section>
{% endblock %}